language: node_js
os: linux
dist: bionic

matrix:
  include:
    - node_js: stable
      script: npm test
      after_script: |
        if [[ x$TRAVIS_NODE_VERSION == xstable ]]; then
          npm i -g coveralls
          npx nyc report --reporter=text-lcov | coveralls
        fi
    - node_js: 12
      script: npm test
    - node_js: 10
      script: npm test
